### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by hatemnsec** [mgeeky/Stracciatella#3]
> The old version of Stracciatella, was accepting cmdlets in any case. 

for instance:
`beacon> stracciatella get-sqlserverinfo
[*] Tasked Beacon to run Stracciatella: get-sqlserverinfo
[+] host called home, sent: 10 bytes
[+] host called home, sent: 268609 bytes
[+] received output:

ComputerName           : HOST
Instance               : HOST\SQLEXPRESS
DomainName             : WORKGROUP
ServiceProcessID       : 2826
`

> while the new version causes some errors,

`beacon> stracciatella Get-SQLServerInfo
[*] Tasked Beacon to run Stracciatella: Get-SQLServerInfo
[+] host called home, sent: 270064 bytes
[+] received output:

ERROR: Get-SQLServerInfo : The term 'Get-SqlServerInfo' is not recognized as the name of a cmdlet, 
ERROR: function, script file, or operable program. Check the spelling of the name, or if a path was 
ERROR: included, verify that the path is correct and try again.
ERROR: At line:1 char:1
ERROR: + Get-SQLServerInfo
ERROR: + ~~~~~~~~~~~~~~~~~
ERROR:     + CategoryInfo          : ObjectNotFound: (Get-SQLServerInfo:String) [], CommandNotFoundExcept 
ERROR:    ion
ERROR:     + FullyQualifiedErrorId : CommandNotFoundException
ERROR:
`

**Comment by mgeeky** [comment]
Hmmm, that's interesting. Never experienced such an issue before. Can you please point me to the specific version number where case sensitivity worked previously?

Best regards,
M.

**Comment by mgeeky** [comment]
Hi,

Finally got around that bug and addressed it in this commit [bfd0e01](https://github.com/mgeeky/Stracciatella/commit/bfd0e0151fabb85f8d977011eb41e16cd13622ac)

Thanks for your issue report.

Regards,
Mariusz.
